### ISSUE TITLE
Errors when initialising a struct with partial keywords or arguments

### ISSUE THREAD

**Issue by yunzheng** [fox-it/dissect.cstruct#102]
When initialising a struct with partial keywords or arguments the other fields become `None` resulting in exceptions, for example when printing the instance of the struct.

When initialising without any arguments it works and all values are 0 as expected. But when you only initialise some of the fields it breaks, example:

```python
from dissect.cstruct import cstruct

C_DEF = """"
struct FooBar {
    uint32  foo;
    uint32  bar;
};
"""

cs = cstruct().load(C_DEF)

print(cs.FooBar())  # works as expected: <FooBar foo=0x0 bar=0x0>
print(cs.FooBar(1, 1)) # works as expected: <FooBar foo=0x1 bar=0x1>

print(cs.FooBar(1)) # breaks, bar=None
print(cs.FooBar(bar=1)) # breaks, foo=None
```

The exception:

```
$ python3 kwargs_init.py 
<FooBar foo=0x0 bar=0x0>
<FooBar foo=0x1 bar=0x1>
Traceback (most recent call last):
  File "/workspaces/dissect.cstruct/examples/kwargs_init.py", line 14, in <module>
    print(cs.FooBar(1)) # breaks, bar=None
    ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dissect.cstruct/dissect/cstruct/types/structure.py", line 388, in __repr__
    value = hex(value)
            ^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by Schamper** [comment]
I think it's more the `repr` that breaks, not the initialization, right? I think this is actually a bug introduced with #101 :smile:

**Comment by yunzheng** [comment]
But if you don't initialise with any arguments it works. So it's more the initialisation behaviour i think.

**Comment by yunzheng** [comment]
The bug also happens before merging #101, in the 4.1 tagged release:

```shell
$ python3 kwargs_init.py 
<FooBar foo=0x0 bar=0x0>
<FooBar foo=0x1 bar=0x1>
Traceback (most recent call last):
  File "/workspaces/dissect.cstruct/examples/kwargs_init.py", line 14, in <module>
    print(cs.FooBar(1)) # breaks, bar=None
    ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dissect.cstruct/dissect/cstruct/types/structure.py", line 384, in __repr__
    f"{k}={hex(self[k]) if (issubclass(f.type, int) and not issubclass(f.type, Pointer)) else repr(self[k])}"
           ^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
```

To be clear in the example, the following works:

```python
print(cs.FooBar())
print(cs.FooBar(foo=1, bar=2))
```

The following breaks, only one field initialised from the two fields:

```python
print(cs.FooBar(foo=1))
```

**Comment by Schamper** [comment]
We looked at the code together and decided it’s best to change the default initialization behavior of None to be the default for that type instead.

**Comment by yunzheng** [comment]
I've currently used the following workaround, which is to initialise it empty first without any arguments, then set the partial values via attributes afterwards, eg:

```python
>>> c = cs.FooBar()
>>> c.foo = 0x1337
>>> print(c)
<FooBar foo=0x1337 bar=0x0>
```
