### ISSUE TITLE
name attribute of unknown Enum values are None

### ISSUE THREAD

**Issue by yunzheng** [fox-it/dissect.cstruct#103]
`dissect.cstruct` enums that are unknown will have `None` as `.name`. Before `dissect.cstruct` v4 it would have the enum name with the value as the name. eg: `MyFancyEnum_1337`.

It's easiest to explain using the following code snippet:

```python
from dissect import cstruct

cdef = """
enum Test : uint16 {
    A = 0,
    B = 1,
    C = 2,
};
"""

cs = cstruct.cstruct()
cs.load(cdef)

for i in range(4):
    enum = cs.Test(i)
    print(f"{i=} {enum=!s} {enum.name=}")
```

With `dissect.cstruct==3.10`:

```
i=0 enum=Test.A enum.name='A'
i=1 enum=Test.B enum.name='B'
i=2 enum=Test.C enum.name='C'
i=3 enum=Test.Test_3 enum.name='Test_3'
```

With `dissect.cstruct==4.2`:

```
i=0 enum=Test.A enum.name='A'
i=1 enum=Test.B enum.name='B'
i=2 enum=Test.C enum.name='C'
i=3 enum=Test.3 enum.name=None
```

I would expect that `enum.name` not to be `None`, but rather `Test_3` or `Test.3` like before.

**Comment by Schamper** [comment]
This was an intentional change when moving to native Python enum types. At least one reason I remember is that it's more predictable (an unknown enum member technically can't have a name), but there may have been other technical implementation reasons as well.

Perhaps we could re-enable this behaviour with a flag, because it can be useful after all. Open for suggestions on that front.

**Comment by yunzheng** [comment]
In native Python IntEnum you cannot initialise an unknown Enum value, so it's useful that this is possible in `dissect.cstruct` without blowing up. I currently use the following workaround for a proper name now:

```python
name = enum.name or str(enum)
```

I noticed that Python 3.11 now has a `boundary=KEEP` option for Flags. Which is something that could maybe also be adopted for `dissect.cstruct` but also with other enums:

https://docs.python.org/3/library/enum.html#enum.FlagBoundary.KEEP

Example below, but this sadly this only works for `Flag` in Python and not `IntEnum` for example:

```python
>>> from enum import Flag, STRICT, auto, KEEP
>>> class MyFancyFlag(Flag, boundary=KEEP):
...     RED = auto()
...     BLUE = auto()
...     GREEN = auto()
...     
>>> MyFancyFlag(1)
<MyFancyFlag.RED: 1>
>>> MyFancyFlag(10)
<MyFancyFlag.BLUE|8: 10>
>>> MyFancyFlag(10).name
'BLUE|8'
```

**Comment by Schamper** [comment]
> In native Python IntEnum you cannot initialise an unknown Enum value, so it's useful that this is possible in `dissect.cstruct` without blowing up. I currently use the following workaround for a proper name now:

I realise it's useful, but the question is, what is the most logical behaviour: a name of `None` (since it's a non-existent enum value, so technically no name has been assigned to that value), or a generated name. Currently I went with a `name` of `None` and a generated `str()` output.

> I noticed that Python 3.11 now has a `boundary=KEEP`

We already emulate the `KEEP` flag: https://github.com/fox-it/dissect.cstruct/blob/09830d2162f72f9712421ec1b82c96ff5620435f/dissect/cstruct/types/enum.py#L184

**Comment by yunzheng** [comment]
> Currently I went with a name of None and a generated str() output.

I think a generated name is better than `None` to avoid any extra error handling or unexpected behaviour. And as long as it's clear from the name that it's non standard. I found the `EnumName_<number>` to be elegant. Either way, i'm fine if it stays with the current design.

> We already emulate the KEEP flag:

It would be nice to have KEEP also available on other enums and not just Flag. Because in dissect.cstruct you can actually construct an Enum with unknown value.

Note that i brought of the KEEP flag because of your earlier comment:

> Perhaps we could re-enable this behaviour with a flag, because it can be useful after all. Open for suggestions on that front.

So I thought that would make a good flag to re-enable this behaviour :)

**Comment by Schamper** [comment]
> So I thought that would make a good flag to re-enable this behaviour :)

Ah I misunderstood then. We already do this behaviour but we explicitly set the `.name` to `None` in there. I meant add a flag somewhere to re-enable generated enum names.

The `.name == None` is consistent with the `KEEP` flag behaviour of Python, by the way:

```python
In [15]: from enum import Flag, KEEP

In [16]: class A(Flag, boundary=KEEP):
    ...:     a = 1
    ...:     b = 2
    ...: 

In [17]: A.a.name
Out[17]: 'a'

In [18]: A(3).name
Out[18]: 'a|b'

In [19]: A(4)
Out[19]: <A: 4>

In [20]: A(4).name

In [21]: A(4).name is None
Out[21]: True
```

**Comment by yunzheng** [comment]
> The .name == None is consistent with the KEEP flag behaviour of Python

Ah I see, in that case I would just keep it that way and I think there is also no need for an extra flag to re-enable it. Using the `enum.name or str(enum)` pattern would work just as fine.

Closing this issue.
