### ISSUE TITLE
Anonymous enums

### ISSUE THREAD

**Issue by d3dave** [fox-it/dissect.cstruct#30]
cstruct fails to parse anonymous enums because the regex requires enums to have a name. We should be able to just treat all enum members as top-level defines.

**Comment by Schamper** [comment]
Good suggestion. The problem is currently twofold: 
- The regex + parsing for enums needs to allow anonymous enums
- Enum values need to be added as constants to the global scope. Currently only the enum name is added and values need to be accessed as `Name.Value`.

**Comment by Schamper** [comment]
This has now been implemented with https://github.com/fox-it/dissect.cstruct/pull/39.
