### ISSUE TITLE
Support integer suffixes

### ISSUE THREAD

**Issue by d3dave** [fox-it/dissect.cstruct#32]
Integers can have unsigned (`U`/`u`), long (`L`/`l`), and long-long (`LL`/`ll`) suffixes. When attempting to parse these we get a `ValueError` (in `expression.py`):

```console
ValueError: invalid literal for int() with base 10: '1U'
```

**Comment by sMezaOrellana** [comment]
I think https://github.com/fox-it/dissect.cstruct/pull/37 closes this

**Comment by Schamper** [comment]
I believe so too, I had hoped GitHub would automatically close this.

**Comment by Schamper** [comment]
I believe so too, I had hoped GitHub would automatically close this.
