### ISSUE TITLE
Cannot use previous enum constants within expressions for following values

### ISSUE THREAD

**Issue by d3dave** [fox-it/dissect.cstruct#41]
If we have an enum like this:

```c
enum test {
  A,
  B,
  C = B,
  D
};
```

we get an error while parsing because `B` is not within the scope yet (all of the constants are added to the global scope only after the entire enum has finished parsing).

**Comment by Schamper** [comment]
This is indeed a current limitation, but we can probably fix that so it behaves as expected. The value of the member is calculated at parse time, so we only need to check if a set value is the name of an existing member, and continue counting from there.

**Comment by d3dave** [comment]
> This is indeed a current limitation, but we can probably fix that so it behaves as expected. The value of the member is calculated at parse time, so we only need to check if a set value is the name of an existing member, and continue counting from there.

Will this handle

```c
enum test {
  A,
  B = A + 3,
  C
}
```
?

**Comment by Schamper** [comment]
It can, we can just throw the expression together with the existing members into the `Expression` class and evaluate the result.

**Comment by Schamper** [comment]
Will be fixed with the linked PR. Turns out we were almost there already, just missing an argument to the `evaluate` call :smile:
