### ISSUE TITLE
Issue when there is union inside structure

### ISSUE THREAD

**Issue by rroshanshaw** [fox-it/dissect.cstruct#48]
suppose there is a structure  and inside that there is union so when i am assigning value to the first variable in union then it show in binary file but if i assign value to second variable in union then in binary file the value is not showing, so can you check why this is happening

**Comment by Schamper** [comment]
This is related to https://github.com/fox-it/dissect.cstruct/pull/44, however I'm rewriting this to be compatible with the upcoming cstruct v4 (https://github.com/fox-it/dissect.cstruct/pull/35). I'm close to a satisfying solution but ran into some minor roadblocks (plus other work stuff). 

If this is important to you, you can checkout #44 for the time being while I work on a solution compatible with #35.

**Comment by Schamper** [comment]
This should be fixed with #49 and #35.
