### ISSUE TITLE
Field __repr__ missing "f" qualifier on the f-string

### ISSUE THREAD

**Issue by burneykb** [fox-it/dissect.cstruct#56]
https://github.com/fox-it/dissect.cstruct/blob/ffbf4f83169d5c6db2448d42c0e2fa5cec5c874a/dissect/cstruct/types/structure.py#L25

Before:
`<Field res0 uint16 : {self.bits}>`

After making it an f-string:
`<Field res0 uint16 : 6>`

I think the fix is as easy as that. Make line 25 use an f-string. Though I'd appreciate if someone could confirm/deny this is the correct solution for this codebase.

**Comment by burneykb** [comment]
If it can be confirmed, I'd be glad to look through the contributing guide and make a PR later this week when I have some free time 👍. It would be my first, if not extremely small, contribution to an open source project 😅

**Comment by Schamper** [comment]
Nice catch, you're absolutely right 😄. Must've happened when we transitioned to f-strings.

Your PR would be very welcome, maybe also nice to create a unit test for it as well!

**Comment by burneykb** [comment]
Sorry for the handholding, but could you help me understand your vision for a unit test? Are you wanting a test case which calls the `__repr__` and looks to see if there are any un-interpolated brackets? Or maybe run the same test on all types which have a  `__repr__`? 

Or maybe I'm off track already 😅  I'll do what feels right for the time being, maybe this discussion is best to have in a PR anyways.
