### ISSUE TITLE
Consider `inspect` module for compilation

### ISSUE THREAD

**Issue by xloem** [fox-it/dissect.cstruct#57]
I noticed there's code duplication in the compiler and wanted to check whether you were aware of the `inspect` module that provides for run-time introspection of the source code of functions.

It seems if source were referenced directly this could ease maintenance and hacking.

**Comment by Schamper** [comment]
Thanks for the suggestion! The compiler has had a big overhaul in the upcoming v4 release: https://github.com/fox-it/dissect.cstruct/blob/refactor-v4/dissect/cstruct/compiler.py

A lot of the previously duplicated code has been removed. We now also use some clever tricks to create (and update) dynamic type classes for each structure: https://github.com/fox-it/dissect.cstruct/blob/refactor-v4/dissect/cstruct/types/structure.py

Of course, if you still have some good ideas or suggestions for this new approach, I'd like to hear them :smile:.

We're ironing out some last few issues/features with v4, and we still need to make all our other `dissect.*` projects compatible, but we expect to merge&release it in the not too distant future!

**Comment by xloem** [comment]
Thanks for your reply.

Will there be a way to compile custom types in the new compiler? I also use custom expression operators.

I noticed the README still references RawType in v4.

**Comment by xloem** [comment]
I do not understand the compiler and rescind my issue for now :)

If you are interested here are the custom operators and types I ended up making for my toy decoddr of an old binary format: https://github.com/xloem/agsutils/blob/72145a256e8f96c16e47591244aa42ef48825435/datafile.py#L11 . Boolean operations, a list item for every set bit in an array, zero terminated strings, version-conditioned fields, length-prefixed arrays, and a simple encryption format.

**Comment by Schamper** [comment]
> Thanks for your reply.
> 
> Will there be a way to compile custom types in the new compiler? I also use custom expression operators.
> 
> I noticed the README still references RawType in v4.

The README indeed still needs to be updated. Custom types will also be supported, but the way you declare those will change a little bit. It's one of the things that still needs a little bit more fleshing out before we merge the v4 refactor/rewrite. I'll be sure to ping you in this thread once we have matured that a little bit further and have some practical examples!

Nice parser by the way! I always love seeing the different kinds of projects that people use cstruct for. Tinkering with (older) games is also a hobby of mine, so I love seeing stuff like that!
