### ISSUE TITLE
Keyword conflicting with Python

### ISSUE THREAD

**Issue by jwnhy** [fox-it/dissect.cstruct#65]
When the parsed structure contains keywords of Python (e.g., `in`), the compiler complains.

```bash
  File "<some-path>/python3.10/site-packages/dissect/cstruct/compiler.py", line 86, in compile
    code_object = compile(
  File "<compiled in>", line 2
    class in(Structure):
          ^^
SyntaxError: invalid syntax
```

A temporary solution I took is to replace all `in` to `_in` then back, which seems a bit ad-hoc.
I wonder if it's possible to fix this in the `cstruct` level?

**Comment by Schamper** [comment]
Oops, that's indeed an oversight. This should be fixable in `cstruct` itself. When compiling the structure we can compare the name to a list of Python reserved keywords and prefix it with an underscore. Some magic may need to be performed to ensure that things like the structure name when printing remain consistent though.

**Comment by sMezaOrellana** [comment]
You can use the keyword module from python https://docs.python.org/3/library/keyword.html
This could be done during the tokenization of the definition we are going to compile

**Comment by Schamper** [comment]
Yes, we also use that module in `flow.record`.

Our current "tokenization" is separate from compilation (compilation is optional). There should be no problem in having a reserved keyword as a structure name, it would only need to be fixed during compilation.

E.g. around here in the current version:
https://github.com/fox-it/dissect.cstruct/blob/main/dissect/cstruct/compiler.py#L77-L81

v4 shouldn't have this issue as we only compile the `_read` method and not an entire class.
